# Generated by Django 4.2.25 on 2025-10-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius', models.FloatField()),
                ('crash_count', models.IntegerField()),
                ('total_injured', models.IntegerField()),
                ('total_killed', models.IntegerField()),
                ('severity_index', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['severity_index'], name='hotspots_ho_severit_e311e0_idx'), models.Index(fields=['crash_count'], name='hotspots_ho_crash_c_0cb8df_idx')],
            },
        ),
    ]
