# Generated by Django 4.2.25 on 2025-10-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crash',
            fields=[
                ('collision_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('crash_date', models.DateTimeField()),
                ('crash_time', models.CharField(blank=True, max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('borough', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('on_street_name', models.CharField(blank=True, max_length=200)),
                ('cross_street_name', models.CharField(blank=True, max_length=200)),
                ('off_street_name', models.CharField(blank=True, max_length=200)),
                ('number_of_persons_injured', models.IntegerField(default=0)),
                ('number_of_persons_killed', models.IntegerField(default=0)),
                ('number_of_pedestrians_injured', models.IntegerField(default=0)),
                ('number_of_pedestrians_killed', models.IntegerField(default=0)),
                ('number_of_cyclist_injured', models.IntegerField(default=0)),
                ('number_of_cyclist_killed', models.IntegerField(default=0)),
                ('number_of_motorist_injured', models.IntegerField(default=0)),
                ('number_of_motorist_killed', models.IntegerField(default=0)),
                ('contributing_factor_vehicle_1', models.CharField(blank=True, max_length=200)),
                ('contributing_factor_vehicle_2', models.CharField(blank=True, max_length=200)),
                ('contributing_factor_vehicle_3', models.CharField(blank=True, max_length=200)),
                ('contributing_factor_vehicle_4', models.CharField(blank=True, max_length=200)),
                ('contributing_factor_vehicle_5', models.CharField(blank=True, max_length=200)),
                ('vehicle_type_code1', models.CharField(blank=True, max_length=50)),
                ('vehicle_type_code2', models.CharField(blank=True, max_length=50)),
                ('vehicle_type_code_3', models.CharField(blank=True, max_length=50)),
                ('vehicle_type_code_4', models.CharField(blank=True, max_length=50)),
                ('vehicle_type_code_5', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-crash_date'],
                'indexes': [models.Index(fields=['crash_date'], name='accidents_c_crash_d_55378b_idx'), models.Index(fields=['borough'], name='accidents_c_borough_a39521_idx'), models.Index(fields=['latitude', 'longitude'], name='accidents_c_latitud_f0224f_idx')],
            },
        ),
    ]
